### ISSUE TITLE
Need Angular 11 support 

### ISSUE THREAD

**Issue by pmathulan** [RFreij/ngx-smart-banner#6] opened 2021-03-31 14:56 UTC
I got the following error: 

: npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: e-commerce-demo@0.0.2
npm ERR! Found: @angular/common@10.0.14
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~10.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.0.0 || ^12.0.0-0" from @angular/cdk@11.2.6
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@">=9.0.0" from @netcreaties/ngx-smart-banner@1.2.2
npm ERR!   node_modules/@netcreaties/ngx-smart-banner
npm ERR!     @netcreaties/ngx-smart-banner@"*" from the root project

**Comment by RFreij** [comment] 2021-04-04 20:17
Hey @pmathulan,

I can install the package without problem in an angular 11 application. Do you have your package.json for me so i can try tor reproduce the error?

**Comment by pmathulan** [comment] 2021-04-05 07:21
@RFreij Here it is

  "dependencies": {
    "@angular/animations": "^11.2.7",
    "@angular/cli": "^11.2.6",
    "@angular/common": "^11.2.7",
    "@angular/compiler": "^11.2.7",
    "@angular/compiler-cli": "^11.2.7",
    "@angular/core": "^11.2.7",
    "@angular/forms": "^11.2.7",
    "@angular/platform-browser": "^11.2.7",
    "@angular/platform-browser-dynamic": "^11.2.7",
    "@angular/platform-server": "^11.2.7",
    "@angular/router": "^11.2.7",
    "@nguniversal/builders": "^11.2.1",
    "@nguniversal/express-engine": "^11.2.1",
    "@types/express": "^4.17.11",
    "@types/node": "^12.20.5",
    "rxjs": "^6.6.7",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1102.6",
    "@angular/language-service": "^11.2.7",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "^6.2.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "^6.1.3",
    "typescript": "^4.1.5"
  }
}``
``

**Comment by RFreij** [comment] 2021-04-17 23:39
@pmathulan i'm sorry i still can't reproduce the issue. I see a package `npm ERR! While resolving: e-commerce-demo@0.0.2`  in your first post. Could you tell me more about that one? 

How are you installing ngx-smart-banner?

**Comment by rvo-tc** [comment] 2021-05-26 10:48
@RFreij We're seeing a similar issue. It seems to be caused by the `"ngx-cookie-service": "^3.0.4"` dependency, which depends on Angular `^9.0.5`. This makes it so this package can't be installed alongside Angular 11.

Maybe changing it to `>=3.0.4` will do the trick, or separating Angular versions in the same way as ngx-cookie-service

**Comment by pmathulan** [comment] 2021-05-31 06:31
> @pmathulan i'm sorry i still can't reproduce the issue. I see a package `npm ERR! While resolving: e-commerce-demo@0.0.2` in your first post. Could you tell me more about that one?
> 
> How are you installing ngx-smart-banner?

@RFreij it's my project name (e-commerce-demo) and project version(0.0.2)

**Comment by RFreij** [comment] 2021-05-31 14:38
@rvo-tc @pmathulan I've released 1.3.0 which removes the dependency for ngx-cookie-service.

**Closed by RFreij** 2021-05-31 14:38 UTC

**Comment by RFreij** [comment] 2021-05-31 15:16
@rvo-tc @pmathulan I've also released https://www.npmjs.com/package/@netcreaties/ngx-smart-banner/v/2.0.0-0 which updates complete repo to angular 12, and builds library with ivy enabled. 

It would be nice you could test this version.
